---
- name: Pull docker image of ToDoList
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Stop Docker Container
      shell: docker stop scientificcalcdevops
        
    - name: Remove Docker Container
      shell: docker rm -f scientificcalcdevops
        
    - name: Remove Docker Image
      shell: docker image rm -f jpray/scientificcalcdevops:latest
        
    - name: Pull calculator devops image
      docker_image:
        name: jpray/scientificcalcdevops:latest
        source: pull
        
    - name: deploy calculator docker container
      docker_container:
        image: jpray/scientificcalcdevops:latest
        name: scientificcalcdevops
        state: started
        ports:
          - "8090:80"
...
